### ISSUE TITLE
Simplify CSS for font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [saas-0326/prj-rev-bwfs-dasmoto#5]
Great job simplifying the CSS for several of the shared properties among multiple selectors. You can simplify it further for the font-weight property, which is also shared among a few selectors, like so

```css
h1, h2, .price {
  font-weight: bold;
}
```
